apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-deployment
  labels:
    app: fs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
      - name: fs-container
        image: lackhoa/fractal-sky:v0.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint
spec:
  selector:
    app: fs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "True"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "True"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: fractalsky.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: entrypoint
          servicePort: 80
  tls:
  - hosts:
    - fractalsky.xyz
    secretName: fs-tls
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: vodangkhoa873@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
