apiVersion: v1
kind: Pod
metadata:
  name: the-pod
  labels:
    name: the-pod
spec:
  containers:
    - name: the-container
      image: lackhoa/fractal-sky:0.1
      ports:
      - containerPort: 80
        name: http
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint
spec:
  selector:
    name: the-pod
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
